FROM python:3.8
ARG STATIC_ARCHIVE

RUN mkdir /home/static
COPY ${STATIC_ARCHIVE} /home/static
RUN tar -xzf /home/static/*.tgz

WORKDIR /home/static
EXPOSE 8000
CMD ["python", "-m", "http.server", "8000"]